import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#FF6B35',
    primaryContainer: '#FFE5DC',
    secondary: '#004E89',
    secondaryContainer: '#D0E7FF',
    tertiary: '#6A994E',
    tertiaryContainer: '#E8F5E0',
    error: '#BA1A1A',
    errorContainer: '#FFDAD6',
    background: '#FFFBFF',
    surface: '#FFFBFF',
    surfaceVariant: '#F4F0EE',
    outline: '#857370',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#3A0A00',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#001D35',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#0F2000',
    onError: '#FFFFFF',
    onErrorContainer: '#410002',
    onBackground: '#201A19',
    onSurface: '#201A19',
    onSurfaceVariant: '#53433F',
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#FFB59B',
    primaryContainer: '#8C2800',
    secondary: '#9DCEFF',
    secondaryContainer: '#003355',
    tertiary: '#C2E0A8',
    tertiaryContainer: '#3D5A1F',
    error: '#FFB4AB',
    errorContainer: '#93000A',
    background: '#201A19',
    surface: '#201A19',
    surfaceVariant: '#53433F',
    outline: '#A08C89',
    onPrimary: '#5A1800',
    onPrimaryContainer: '#FFDBD0',
    onSecondary: '#003355',
    onSecondaryContainer: '#D0E7FF',
    onTertiary: '#1F3700',
    onTertiaryContainer: '#E8F5E0',
    onError: '#690005',
    onErrorContainer: '#FFDAD6',
    onBackground: '#EDE0DD',
    onSurface: '#EDE0DD',
    onSurfaceVariant: '#D8C2BE',
  },
};

